name = "NNMER"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "474c4f0a86c7806bbf5ab5d65dff34b632d501f01b8226d893e77da7ff947f87"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
