name = "NNMER"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef2c131c563d6e70a51cca08842e02fb813e892305ef0c14b6dacf3869993e1e"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
