name = "NNMER"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815fb61958c2aa8452c209f01908de2dd1699aeec044e20211dfef35f1a1a6fa"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
