name = "NNMER"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf808aa2cfb7f2324b09665c8691f2419f6283a5e5bfbed241f135acb38cb64d"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
