name = "NNMER"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b453fb829ddb9675f4a01751a26676435ef9539160e417f82f10761157b66412"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
