name = "NNMER"
author = "Neddimus Maximus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a5240c87fa63af46a8a89af43cae92c11847f21da65525b43466021f038ce76"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
